import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CineMax</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Movies</h1>

        <Link href="/search">Go to Search</Link>

        <ul>
          {list.map((item) => (
            <li>
              <a href={`/movie/${item.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width="150"
                />
                <br />
                <label>{item.title}</label>
              </a>
            </li>
          ))}
        </ul>

        <Link href="/about">About Me</Link>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/trending");
  const json = await res.json();
  return {
    props: {
      list: json.list,
    },
  };
}
