import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Search() {
  const [searchText, setSearchText] = useState("");
  const [filterMovie, setFilterMovie] = useState([]);

  const handleSearch = async () => {
    if (searchText) {
      const result = await fetch(
        `http://localhost:3000/api/search?q=${searchText}`
      );
      const json = await result.json();
      setFilterMovie(json.list);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CineMax</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Filter</h1>

        <input
          type="text"
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
        ></input>
        <button onClick={handleSearch}>Search</button>

        <hr />

        <ul>
          {filterMovie.map((item) => (
            <li>
              <a href={`/movie/${item.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width="150"
                />
                <br />
                <label>{item.title}</label>
              </a>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}
